version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    env_file:
      - agent-workflow/.env
    ports:
      - "8000:8000"
    networks:
      - agentnet
    volumes:
      # Persist generated data and logs locally during development (optional)
      - ./data:/app/agent-workflow/data

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
      args:
        VITE_API_BASE_URL: http://backend:8000
    depends_on:
      - backend
    environment:
      - VITE_API_BASE_URL=http://backend:8000
    ports:
      - "80:80"
    networks:
      - agentnet

networks:
  agentnet:
    driver: bridge
